### ISSUE TITLE
Error when running remnux upgrade 

### ISSUE THREAD

**Issue by Ch4kr4k** [REMnux/remnux-cli#89]
while trying to upgrade remnux to latest v2022 i face This is the same issue that was raised before i have read that issue and try to find out what was causing and tried to fix , but i could not fix it running `sudo remnux upgrade`  gave this error 
```
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

```
remnux version is 
```
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: v2021.15.2
```
it is a focal version of remnux 
`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

```
saltstack of current remnux version
[saltstack.log](https://github.com/REMnux/remnux-cli/files/9066363/saltstack.log)
saltstack of the remnux version that im trying to upgrade to
[salstack_v2022.15.log](https://github.com/REMnux/remnux-cli/files/9066371/salstack_v2022.15.log)

This is on a freshly installed vm on virtualbox
hoping for your answers and solutions soon
thanking you in advance

**Comment by digitalsleuth** [comment]
Hi @BL4CK-R34P3R , it looks like the issue was a network connection issue with PolarProxy. Unfortunately, their site sometimes has connectivity issues and downloads will occasionally fail. 
Everything else in the installation installed properly, so your VM should work perfectly fine. It just doesn't have an updated version of PolarProxy.

**Comment by Ch4kr4k** [comment]
@digitalsleuth 
So,  what should I do sir

**Comment by BL4CK-R34P3R** [comment]
So what should I do sir, just wait and retry again sometimes,
I ll rerun again and attached the saltstack

**Comment by Ch4kr4k** [comment]
here is the saltstack again from the folder `/var/cache/remnux/cli/v2022.26.3`  tried looking into saltstack.log but does
not understand a thing
[saltstack.log](https://github.com/REMnux/remnux-cli/files/9068731/saltstack.log)

**Comment by Ch4kr4k** [comment]
if it is the problem of polar proxy it will be because of the polarproxy.sls
since that was designed for polarproxy 0.9.6  but the download link given there is now for polarproxy 0.9.7 and does not match
i think the polarproxy should be somewhat like this
```
# Description: Intercept and decrypt TLS traffic.
# Category: Explore Network Interactions: Monitoring
# Author: NETRESEC AB
# License: Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0) License: https://www.netresec.com/?page=PolarProxy
# Notes: polarproxy

remnux-polarproxy-source:
  file.managed:
    - name: /usr/local/src/remnux/files/PolarProxy_0-9-7_linux-x64.tar.gz
    - source: https://www.netresec.com/?download=PolarProxy
    - source_hash: sha256=7995593700748946082fcb3e56f182d86f289a28b64ba9ee7cedca63a0a5d69d

    - makedirs: True
    - replace: False

remnux-polarproxy-archive:
  archive.extracted:
    - name: /usr/local/polarproxy/
    - source: /usr/local/src/remnux/files/PolarProxy_0-9-7_linux-x64.tar.gz
    - enforce_toplevel: False
    - force: true
    - watch:
      - file: remnux-polarproxy-source

/usr/local/polarproxy/PolarProxy:
  file.managed:
    - mode: 755
    - replace: False
    - watch:
      - archive: remnux-polarproxy-archive

remnux-polarproxy-wrapper:
  file.managed:
    - name: /usr/local/bin/polarproxy
    - mode: 755
    - replace: False
    - watch:
      - file: /usr/local/polarproxy/PolarProxy
    - contents:
      - '#!/bin/bash'
      - /usr/local/polarproxy/PolarProxy ${*}

```
